[package]
name = "hozondb-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { workspace = true}
prost = {workspace = true}
crc32fast = { workspace = true }
comfy-table = { workspace = true }

[dev-dependencies]

[build-dependencies]
tonic-build = { workspace = true}

[[bin]]
name = "benchmark"
path = "src/benchmark/main.rs"