[package]
name = "hozondb-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { workspace = true}
hozondb-core = { path = "../core"}
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]

[build-dependencies]