syntax = "proto3";

package hozondb;

service HozonDBService {
    rpc Execute(ExecuteRequest) returns (ExecuteResponse);
    rpc Query(QueryRequest) returns (stream QueryResponse);
}

message ExecuteRequest {
    string sql = 1;
}

message ExecuteResponse {
    oneof kind {
        string message = 1;
        ResultSet rows = 2;
    }
}

message ResultSet {
    repeated Row rows = 1;
    repeated string columns = 2;
}

message Row {
    repeated Value values = 1;
}

message Value {
    oneof kind {
        int32 integer = 1;
        string text = 2;
        bool boolean = 3;
        bool is_null = 4;
    }
}

message QueryRequest {
    string sql = 1;
}

message QueryResponse {
    oneof payload {
        Headers headers = 1;
        Row row = 2;
    }
}

message Headers {
    repeated string columns = 1;
}